# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_umax <- function(P, b) {
    .Call('_gfilogisreg_get_umax', PACKAGE = 'gfilogisreg', P, b)
}

get_vmin_i <- function(P, b, i, mu) {
    .Call('_gfilogisreg_get_vmin_i', PACKAGE = 'gfilogisreg', P, b, i, mu)
}

get_vmin <- function(P, b, mu) {
    .Call('_gfilogisreg_get_vmin', PACKAGE = 'gfilogisreg', P, b, mu)
}

get_bounds <- function(P, b) {
    .Call('_gfilogisreg_get_bounds', PACKAGE = 'gfilogisreg', P, b)
}

rcd <- function(n, P, b) {
    .Call('_gfilogisreg_rcd', PACKAGE = 'gfilogisreg', n, P, b)
}

loop1 <- function(H, hbreaks, Points, pbreaks, y, Xt) {
    .Call('_gfilogisreg_loop1', PACKAGE = 'gfilogisreg', H, hbreaks, Points, pbreaks, y, Xt)
}

lloop1 <- function(H, hbreaks, Points, pbreaks, y, Xt) {
    .Call('_gfilogisreg_lloop1', PACKAGE = 'gfilogisreg', H, hbreaks, Points, pbreaks, y, Xt)
}

