# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xf2 <- function(u, P, b, mu, j) {
    invisible(.Call('_gfilogisreg_xf2', PACKAGE = 'gfilogisreg', u, P, b, mu, j))
}

get_umax <- function(P, b, init) {
    .Call('_gfilogisreg_get_umax', PACKAGE = 'gfilogisreg', P, b, init)
}

get_vmin_i <- function(P, b, i, mu) {
    .Call('_gfilogisreg_get_vmin_i', PACKAGE = 'gfilogisreg', P, b, i, mu)
}

get_vmin <- function(P, b, mu) {
    .Call('_gfilogisreg_get_vmin', PACKAGE = 'gfilogisreg', P, b, mu)
}

get_vmax <- function(P, b, mu) {
    .Call('_gfilogisreg_get_vmax', PACKAGE = 'gfilogisreg', P, b, mu)
}

get_bounds <- function(P, b, init) {
    .Call('_gfilogisreg_get_bounds', PACKAGE = 'gfilogisreg', P, b, init)
}

rcd <- function(n, P, b, init) {
    .Call('_gfilogisreg_rcd', PACKAGE = 'gfilogisreg', n, P, b, init)
}

loop1 <- function(H, Points, y, Xt) {
    .Call('_gfilogisreg_loop1', PACKAGE = 'gfilogisreg', H, Points, y, Xt)
}

